### ISSUE TITLE
github offline

### ISSUE THREAD

**Issue by motp** [pengutronix/sysgit#1]
Thanks for this nice project, however: Github is not accessible from my ipv6-only system ... 
Could you please use an IPv6 capable git hosting service?

root@debian8template:~/git# git clone https://github.com/pengutronix/sysgit
Cloning into 'sysgit'...
fatal: unable to access 'https://github.com/pengutronix/sysgit/': Couldn't connect to server

**Comment by Farom** [comment]
yes ... github ... you know.
